### ISSUE TITLE
Selected option isn't displayed in the drop down for Urgenta

### ISSUE THREAD

**Issue by codrutas1** [code4romania/ro-help#351] opened 2020-04-21 23:30 UTC
1. Open https://rohelp.ro/ro/?county=BACAU&city=Bac%C4%83u&urgency=medium
Expected result: all the selected options should be displayed in drop downs
Actual result:  Moderate (or "medium"?)  is not displayed in Urgenta
![Urgenta](https://user-images.githubusercontent.com/6797637/79924625-ed2acd00-8440-11ea-8c82-228a46cded60.png)

**Comment by catileptic** [comment] 2020-04-22 14:42
This is what your URL looks like on me. Can you make sure this issue reproduces?

![Screenshot 2020-04-22 at 17 41 53](https://user-images.githubusercontent.com/14028425/79995954-8fd66080-84c0-11ea-9ae1-f37509e9d605.png)

**Comment by catileptic** [comment] 2020-04-22 14:42
(closed by mistake, I apologise)

**Comment by codrutas1** [comment] 2020-04-22 18:18
Hi, considering that for the other two drop downs the selected values remain displayed (e.g. Bacau is displayed in the first and second drop-down) shouldn't we see "Moderat" instead of "Urgenta"  in the third one?
If you select an option in the third dropdown, does it remain displayed for the user?
For me, it looks like in the Actual Result section of the below image
![expected vs actual](https://user-images.githubusercontent.com/6797637/80018409-a2f82900-84de-11ea-8c52-05106718386d.png)

**Comment by catileptic** [comment] 2020-04-24 13:50
There was an Issue - though I can't seem to find it now - or a feature request to treat the urgency differently from the city. This is because seeing "Bacău" is self-explanatory - you can immediately assume that the list only displays needs form Bacău. However, seeing "Moderat" instead of "Urgență" cna be confusing to new users, because the word "Moderat" (or any of their others) on their own don't imply the concept of "urgency". 

I'm closing this Issue for now. Please don't take it as an end to this discussion - if you feel that this is the wrong choice to make, re-open the issue and pursue the matter further. :)

**Closed by catileptic** 2020-04-24 13:50 UTC

**Comment by codrutas1** [comment] 2020-04-24 18:58
:) No worries, thank you for explaining.
